In [58]:
#importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt




In [59]:
#reading the data
data = pd.read_csv("creditcard.csv",index_col=False)


In [60]:
#checking for null values
data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [61]:
#seperating the dataset into indeoendent and dependent variable
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

In [62]:
print(y)

[0 0 0 ... 0 0 0]


In [63]:
#filling the missing value with mean value
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x)
x = imputer.transform(x)

In [64]:
#seperating dataset intotraining and testing data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [65]:
print(y_test)

[0 0 0 ... 0 0 0]


In [81]:
#building and training the model
from sklearn.ensemble import GradientBoostingClassifier
Classfier = GradientBoostingClassifier(n_estimators=10,random_state=1)
Classfier.fit(x_train,y_train)

GradientBoostingClassifier(n_estimators=10, random_state=1)

In [83]:
#prediction of test variables
y_pred = Classfier.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))


[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [84]:
#using cross validation method
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = Classfier, X = x_train, y = y_train, cv = 2)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 99.86 %
Standard Deviation: 0.04 %


In [85]:
#printing confusion matrix and accuracy score
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = Classfier.predict(x_test)
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[56844    17]
 [   26    75]]


0.9992451107756047

In [76]:
#preforming precision_score,recall_score and f1_score
from sklearn.metrics import precision_score,recall_score,f1_score
precision = precision_score(y_pred,y_test)
recall = recall_score(y_test, y_pred)
f1score = f1_score(y_test, y_pred)



In [77]:
#printing precision_score,recall_score and f1_score
print(precision)
print(recall)
print(f1score)

0.7425742574257426
0.7425742574257426
0.77720207253886


In [82]:
#predicting a random value
y_pred1 = Classfier.predict([[500,-2.459,1.082,2.73,1.47,-0.53,0.76,0.53,0.18,0.63,0.10,-0.75,-0.71,-1.09,-0.51,1.76,0.77,0.507,0.25,0.603,0.55,-0.18,0.477,-0.51014,0.66,0.45,-0.89,0.335,-0.51,200.62]])


In [80]:
print(y_pred1)

[0]
